### ISSUE TITLE
[feature] : Add hover effect in "product" list on Navbar

### ISSUE THREAD

**Issue by Sa24miksha** [DagsHub/Hacktoberfest-Issues#2]
🔖 Feature description
"Resources" and "product" are only two dropdown on the Navbar , while clicking on the resources , the list when hovered are highlighted 
but while hovering over product list , there is no hover effect.

🎤 Why is this feature needed ?
Improved user experience: Adding hover effects can improve precision and clickability.

**Comment by Abhi-gits** [comment]
please assign this to me...i am interested to work on it

**Comment by AD11-web** [comment]
@Sa24miksha Assign me> so I can proceed to work on it...

**Comment by prithvihehe** [comment]
@Sa24miksha could you please assign me this issue if it has not already been assigned, as it is something from my domain, i feel i'd be able to work much better on it

**Comment by Abhi-gits** [comment]
@yonomitt please mention where could i get repository to work on given issue. I have reviewed issue on DogsHub website but not getting code repo to work on

**Comment by yonomitt** [comment]
@Abhi-gits I assigned this before I realized what the issue was for. The DagsHub website is not a public repo, so we cannot take contributions for it. Sorry about that.
