### ISSUE TITLE
Request to Update Twitter Logo in Footer Section 

### ISSUE THREAD

**Issue by moheyt** [DagsHub/Hacktoberfest-Issues#5]
I have identified that the Twitter logo displayed in the footer section of website is outdated, and it is crucial to keep branding up to date with the latest elements provided by Twitter.

![Screenshot 2023-10-24 221025](https://github.com/DagsHub/Hacktoberfest-Issues/assets/85775976/728ff6f3-fa35-4cbb-bd50-dccbb81bb2d0)

I would like to work on this. Can you assign it to me? #hacktoberfest

**Comment by ashutuptiwari** [comment]
If @moheyt removes his assignment in the future, assign this to me. Emphasis on 'if'

**Comment by yonomitt** [comment]
@moheyt The DagsHub website is not a public repo, so we cannot take contributions for it. Sorry about that.
